export const stats = [
  {
    id: "produce",
    title: "Total Produce",
    value: "12",
    description: "Items in inventory",
    icon: "package",
    color: "#bd9e4b",
  },
  {
    id: "fresh",
    title: "Fresh Items",
    value: "8",
    description: "Good condition",
    icon: "leaf",
    color: "#22c55e",
  },
  {
    id: "equipment",
    title: "Equipment",
    value: "5",
    description: "Available to share",
    icon: "tool",
    color: "#f59e0b",
  },
  {
    id: "markets",
    title: "Markets",
    value: "3",
    description: "Within 10km",
    icon: "trending-up",
    color: "#3b82f6",
  },
];

export const notifs = [
  {
    id: 1,
    type: "freshness",
    title: "Tomatoes Expiring Soon",
    description: "3 tomatoes will expire in 2 days",
    timestamp: "2 hours ago",
    icon: "clock",
    color: "#eab308",
    read: false,
  },
  {
    id: 2,
    type: "equipment",
    title: "Equipment Booking Confirmed",
    description: "Your diesel pump booking is confirmed for tomorrow",
    timestamp: "5 hours ago",
    icon: "zap",
    color: "#22c55e",
    read: false,
  },
  {
    id: 3,
    type: "market",
    title: "New Market Added Nearby",
    description: "A new vegetable market opened 5km away",
    timestamp: "1 day ago",
    icon: "map-pin",
    color: "#3b82f6",
    read: false,
  },
  {
    id: 4,
    type: "community",
    title: "New Comment on Your Post",
    description: "Farmer Rajesh commented on your offer",
    timestamp: "2 days ago",
    icon: "message-circle",
    color: "#8b5cf6",
    read: true,
  },
  {
    id: 5,
    type: "freshness",
    title: "Expired Items Alert",
    description: "2 items have expired and should be removed",
    timestamp: "3 days ago",
    icon: "alert-circle",
    color: "#ef4444",
    read: true,
  },
];
